name: monitoring_kalori
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  hexcolor: ^2.0.7
  email_validator: ^2.1.17
  firebase_core: 1.20.1
  firebase_auth: 3.6.3
  select_form_field: 2.2.0
  cloud_firestore: 3.4.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

